/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.DAO.ClienteDAO;
import Control.DAO.ComidaDAO;
import Modelo.Sesion;
import Modelo.Usuario;
import Combo.Combos.*;
import Combo.Decorator.*;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;

/**
 *
 * @author USUARIO
 */
public class ComidaGUI extends javax.swing.JPanel {

    /**
     * Creates new form Comida
     */
    private ComidaDAO baseDatos = new ComidaDAO();
    private ClienteDAO baseDatos2 = new ClienteDAO();
    List<String> id = new ArrayList<>();
    List<String> cantidades = new ArrayList<>();
    PerfilUser user = new PerfilUser((Usuario) Sesion.getInstance().getPersona());
    String arregloCombos[] = { "Seleccione","Combo Basico","Combo Junior", 
			"Combo Mediano", "Combo Grande" };
            
    public ComidaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadioBoton = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imgPopSal = new javax.swing.JLabel();
        titulo5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        radioBoton = new javax.swing.JRadioButton();
        radioBoton1 = new javax.swing.JRadioButton();
        radioBoton2 = new javax.swing.JRadioButton();
        botonComprar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titulo7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 227, 227));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setText("COMIDAS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 260, 60));

        jPanel3.setPreferredSize(new java.awt.Dimension(1720, 2000));
        jPanel3.setLayout(null);

        imgPopSal.setBackground(new java.awt.Color(255, 255, 255));
        imgPopSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Comida/1.png"))); // NOI18N
        jPanel3.add(imgPopSal);
        imgPopSal.setBounds(200, 310, 210, 270);

        titulo5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        titulo5.setText("Adiciones");
        jPanel3.add(titulo5);
        titulo5.setBounds(940, 180, 240, 50);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Pago:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(1340, 340, 67, 31);

        lblTotal.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jPanel3.add(lblTotal);
        lblTotal.setBounds(1400, 270, 280, 60);

        grupoRadioBoton.add(radioBoton);
        radioBoton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioBoton.setText("Tarjeta de credito");
        radioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBotonActionPerformed(evt);
            }
        });
        jPanel3.add(radioBoton);
        radioBoton.setBounds(1340, 430, 142, 23);

        grupoRadioBoton.add(radioBoton1);
        radioBoton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioBoton1.setText("PSE");
        radioBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton1ActionPerformed(evt);
            }
        });
        jPanel3.add(radioBoton1);
        radioBoton1.setBounds(1340, 400, 45, 23);

        grupoRadioBoton.add(radioBoton2);
        radioBoton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioBoton2.setText("Efectivo (efecty,baloto,etc..)");
        radioBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton2ActionPerformed(evt);
            }
        });
        jPanel3.add(radioBoton2);
        radioBoton2.setBounds(1340, 380, 214, 23);

        botonComprar.setBackground(new java.awt.Color(204, 0, 51));
        botonComprar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botonComprar.setForeground(new java.awt.Color(255, 255, 255));
        botonComprar.setText("Comprar");
        botonComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonComprar.setEnabled(false);
        botonComprar.setFocusable(false);
        botonComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonComprarMouseEntered(evt);
            }
        });
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });
        jPanel3.add(botonComprar);
        botonComprar.setBounds(1350, 480, 130, 25);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Combo Basico", "Combo Junior", "Combo Personal", "Combo Mediano", "Combo Grande", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(230, 180, 500, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(460, 270, 340, 370);

        titulo7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        titulo7.setText("Menu de Combos");
        jPanel3.add(titulo7);
        titulo7.setBounds(390, 130, 240, 50);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("Adicionar Perro Caliente");
        jCheckBox1.setActionCommand("Adicionar Gaseosa Grande\n");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(900, 600, 280, 40);

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Adicionar Botella de Agua");
        jCheckBox2.setEnabled(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(900, 280, 230, 40);

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox3.setText("Adicionar Chocolatina Pequeña\n");
        jCheckBox3.setEnabled(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox3);
        jCheckBox3.setBounds(900, 320, 280, 40);

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox4.setText("Adicionar Chocolatina Grande");
        jCheckBox4.setEnabled(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox4);
        jCheckBox4.setBounds(900, 360, 280, 40);

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox5.setText("Adicionar Gaseosa Mediana");
        jCheckBox5.setEnabled(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox5);
        jCheckBox5.setBounds(900, 400, 280, 40);

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox6.setText("Adicionar Gaseosa Grande");
        jCheckBox6.setActionCommand("Adicionar Gaseosa Grande\n");
        jCheckBox6.setEnabled(false);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox6);
        jCheckBox6.setBounds(900, 440, 280, 40);

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox7.setText("Adicionar Hamburguesa");
        jCheckBox7.setActionCommand("Adicionar Gaseosa Grande\n");
        jCheckBox7.setEnabled(false);
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox7);
        jCheckBox7.setBounds(900, 480, 280, 40);

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox8.setText("Adicionar Nachos");
        jCheckBox8.setActionCommand("Adicionar Gaseosa Grande\n");
        jCheckBox8.setEnabled(false);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox8);
        jCheckBox8.setBounds(900, 520, 280, 40);

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox9.setText("Palomitas Dulces");
        jCheckBox9.setActionCommand("Adicionar Gaseosa Grande\n");
        jCheckBox9.setEnabled(false);
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox9);
        jCheckBox9.setBounds(900, 560, 280, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel8.setText("Comida");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(1350, 160, 200, 60);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel9.setText("Total:  $");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(1220, 270, 180, 60);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1720, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void radioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBotonActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex()!=0) {
            botonComprar.setEnabled(true);
        }
    }//GEN-LAST:event_radioBotonActionPerformed

    private void radioBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex()!=0) {
            botonComprar.setEnabled(true);
        }
    }//GEN-LAST:event_radioBoton1ActionPerformed

    private void radioBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex()!=0) {
            botonComprar.setEnabled(true);
        }

    }//GEN-LAST:event_radioBoton2ActionPerformed

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        // TODO add your handling code here:
        int contador = 0;
        int puntAct = user.getU().getPuntos();
        int puntos = 5 * contador;
        baseDatos2.modifPuntos("" + user.getU().getId(), puntAct + puntos);
        user.getU().setPuntos(puntAct + puntos);
        if (puntAct + puntos >= 100) {
            LocalDate fecha = LocalDate.now();
            baseDatos2.modifFecha("" + user.getU().getId(), "" + fecha);
        }
        JFrame exito = new JFrame();
        JOptionPane.showMessageDialog(exito, "¡Su compra ha sido exitosa!");

    }//GEN-LAST:event_botonComprarActionPerformed

    private void botonComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseEntered
        // TODO add your handling code here:
        if ( (jComboBox1.getSelectedIndex()!=0) && (radioBoton.isSelected() == true || radioBoton1.isSelected() == true || radioBoton2.isSelected() == true)) {
            botonComprar.setEnabled(true);
        } else {
            botonComprar.setEnabled(false);
        }
    }//GEN-LAST:event_botonComprarMouseEntered

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            verificaSeleccion();
		
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprar;
    private javax.swing.ButtonGroup grupoRadioBoton;
    private javax.swing.JLabel imgPopSal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton radioBoton;
    private javax.swing.JRadioButton radioBoton1;
    private javax.swing.JRadioButton radioBoton2;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo7;
    // End of variables declaration//GEN-END:variables


    
    public void actionPerformed(ActionEvent e) 
	{
            
        }
    
    private void verificaSeleccion() {
		if (jComboBox1.getSelectedIndex()!=0)
		{
			habilitar(true);
			if (jComboBox1.getSelectedIndex()==1) 
			{
                            Combo combo1 =new ComboBase();
				jTextArea1.setText(combo1.getDescripcion());
				lblTotal.setText(""+combo1.Costo());
			}
			else if (jComboBox1.getSelectedIndex()==2) 
			{
				Combo combo2 =new ComboJunior();
				jTextArea1.setText(combo2.getDescripcion());
				lblTotal.setText(""+combo2.Costo());
			}
			else if (jComboBox1.getSelectedIndex()==3) 
			{
				Combo combo3 =new ComboPersonal();
				jTextArea1.setText(combo3.getDescripcion());
				lblTotal.setText(""+combo3.Costo());
			}
                        else if (jComboBox1.getSelectedIndex()==4) 
			{
				Combo combo4 =new ComboMediano();
				jTextArea1.setText(combo4.getDescripcion());
				lblTotal.setText(""+combo4.Costo());
			}
                        else if (jComboBox1.getSelectedIndex()==5) 
			{
				Combo combo5 =new ComboGrande();
				jTextArea1.setText(combo5.getDescripcion());
				lblTotal.setText(""+combo5.Costo());
			}
			
		}
		else{
			jTextArea1.setText("");
			lblTotal.setText("");
			habilitar(false);
		}
			
	}
    private void Adicion(Combo combo){
        if (jCheckBox1.isSelected()){
            combo=new AdicionAgua(combo);    
        }
        if (jCheckBox2.isSelected()){
            combo=new AdicionChocolatinaGrande(combo);    
        }
        if (jCheckBox3.isSelected()){
            combo=new AdicionChocolatinaPequeña(combo);    
        }
        if (jCheckBox4.isSelected()){
            combo=new AdicionGaseosaGrande(combo);    
        }
        if (jCheckBox5.isSelected()){
            combo=new AdicionGaseosaMediana(combo);    
        }
        if (jCheckBox6.isSelected()){
            combo=new AdicionHamburguesa(combo);    
        }
        if (jCheckBox7.isSelected()){
            combo=new AdicionNachos(combo);    
        }
        if (jCheckBox8.isSelected()){
            combo=new AdicionPalomitasDulces(combo);    
        }
	if (jCheckBox9.isSelected()){
            combo=new AdicionPerroCaliente(combo);    
        }		
        jTextArea1.setText("Combo: "+combo.getDescripcion());
        lblTotal.setText(""+combo.Costo());
    }
    
    private void habilitar(boolean b) 
	{
            jCheckBox1.setEnabled(b);
            jCheckBox2.setEnabled(b);
            jCheckBox3.setEnabled(b);
            jCheckBox4.setEnabled(b);
            jCheckBox5.setEnabled(b);
            jCheckBox6.setEnabled(b);
            jCheckBox7.setEnabled(b);
            jCheckBox8.setEnabled(b);
            jCheckBox9.setEnabled(b);
            
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            jCheckBox7.setSelected(false);
            jCheckBox8.setSelected(false);
            jCheckBox9.setSelected(false);
        }
}
