package Vista;

import Control.DAO.PeliculaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

import Modelo.Pelicula; 
import Modelo.Sesion;
public class PeliculaGUI extends javax.swing.JPanel {


    Pelicula peli;
    int peli_id;
    private PeliculaDAO baseDatos = new PeliculaDAO();
    private JFrame frame;
    private static List<JButton> botones = new ArrayList<>();

    private Sesion sesion;

    public PeliculaGUI(Pelicula peli, JFrame frame, int peli_id) {
        initComponents();
        this.frame = frame;
        this.peli = peli;
        this.peli_id = peli_id;
        info();
        funciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 227, 227));
        setPreferredSize(new java.awt.Dimension(1920, 960));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setText("BOLETERIA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 890, 60));

        jPanel3.setBackground(new java.awt.Color(235, 235, 235));
        jPanel3.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Imagen Pelicula");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 30, 370, 420);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOMBRE PELICULA");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 590, 360, 100);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DESCRIPCION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 910, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 400));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCaretColor(new java.awt.Color(51, 51, 51));
        jTextArea1.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextArea1.setEnabled(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 55, 910, 300);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FUNCIONES");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 360, 910, 60);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 165, 1270, 45);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 430, 910, 90);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(420, 30, 910, 530);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1720, 730));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Pelicula/Estrella Dorada.png"))); // NOI18N
        jLabel10.setText("PUNTUA LA PELICULA");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 870, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        JFrame puntuar = new Puntuar("Pelicula", this.peli_id);
        puntuar.setVisible(true);
        puntuar.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel10MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void info() {
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(peli.getDirectorio_img()))); // NOI18N
        jLabel1.setText("");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 30, 360, 550);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(peli.getNombre());
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 590, 360, 100);

        jTextArea1.append(peli.getDescripcion());
        jTextArea1.setLineWrap(true);
    }

    public void funciones() {
        sesion = Sesion.getInstance();
        char pelicu = peli.getDirectorio_img().charAt(peli.getDirectorio_img().length() - 5);
        List<String> funci = baseDatos.pelicula(Character.getNumericValue(pelicu));
        List<Integer> id = new ArrayList<>();

        List<String> funcion = new ArrayList<>();
        for (int i = 1; i < funci.size(); i += 2) {
            id.add(Integer.parseInt(funci.get(i)));
        }
        for (int i = 0; i < funci.size(); i += 2) {
            funcion.add(funci.get(i));
        }
        for (int i = 0; i < funcion.size(); i++) {
            int aux = id.get(i);
            JButton boton = new JButton();
            boton.setBackground(new java.awt.Color(255, 255, 255));
            boton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
            boton.setText(funcion.get(i));
            boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            boton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    if (sesion.isLogged()) {
                        frame.getContentPane().removeAll();
                        frame.getContentPane().add(MainPage.getEncabezado()).setBounds(0, 0, 1920, 120);
                        frame.getContentPane().add(new SillasPanel(aux)).setBounds(0, 120, 1920, 960);
                        frame.getContentPane().revalidate();
                        frame.getContentPane().repaint();
                    } else {
                        MainPage.getFrameLogin().setVisible(true);
                        frame.setEnabled(false);
                    }

                }
            });
            jPanel4.add(boton);
            botones.add(boton);
        }

    }

}
